"""Labgrid venue for the virtual lab — VMs as labgrid places.

One running virtual-lab instance (scripts/virtual-lab.py) becomes two
places on the shared coordinator:

    vlab-<lane>-owrt     OpenWrt gateway VM  (SSH + serial over TCP)
    vlab-<lane>-client   Debian client VM    (SSH + serial over TCP)

The VM lifecycle stays with virtual-lab.py; this module only EXPORTS a
running lab. Serial access is the QEMU unix-socket console fronted by a
socat TCP relay, exported as a ``NetworkSerialPort`` resource — so
``labgrid-client -p vlab-<lane>-owrt console`` works from anywhere the
coordinator is reachable, and the exclusivity contract (acquire/release)
covers VMs exactly like it covers physical routers.

The labgrid python package is NOT imported: the exporter is a subprocess
on the VM host and the client binary is driven as a subprocess, so unit
tests inject a fake runner and CI needs no coordinator at all (same
philosophy as lib/labgrid_venue.py).
"""

from __future__ import annotations

import re
import shlex
from dataclasses import dataclass

SERIAL_PORT_BASE = 46000
DEFAULT_COORDINATOR = "ai-legion:20408"
DEFAULT_LANE = "default"
DEFAULT_OWRT_ADDRESS = "10.99.99.1"
DEFAULT_CLIENT_ADDRESS = "10.99.99.100"
SSH_PORT = 22

_LANE_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,30}$")


class VlabExportError(RuntimeError):
    """Export operation failed — message never carries secrets."""


def _check_lane(lane: str) -> str:
    if not lane or not _LANE_RE.match(lane):
        raise VlabExportError(
            f"lane {lane!r} must match { _LANE_RE.pattern } (lowercase slug)"
        )
    return lane


def place_names(lane: str = DEFAULT_LANE) -> tuple[str, str]:
    """(owrt place, client place) for a lane."""
    _check_lane(lane)
    return f"vlab-{lane}-owrt", f"vlab-{lane}-client"


def serial_ports(lane_num: int = 0, base: int = SERIAL_PORT_BASE) -> tuple[int, int]:
    """Deterministic (owrt, client) TCP ports; one lane = 2 ports."""
    if lane_num < 0 or lane_num > 999:
        raise VlabExportError("lane_num must be 0..999")
    return base + lane_num * 2, base + lane_num * 2 + 1


@dataclass(frozen=True)
class VlabExportSpec:
    """Everything the exporter config and relay scripts need."""

    lane: str = DEFAULT_LANE
    coordinator: str = DEFAULT_COORDINATOR
    serial_host: str = "127.0.0.1"
    owrt_address: str = DEFAULT_OWRT_ADDRESS
    client_address: str = DEFAULT_CLIENT_ADDRESS
    serial_port_owrt: int = SERIAL_PORT_BASE
    serial_port_client: int = SERIAL_PORT_BASE + 1

    @property
    def places(self) -> tuple[str, str]:
        return place_names(self.lane)


def exporter_config_yaml(spec: VlabExportSpec) -> str:
    """Exporter config: one top-level group per place (group == place
    name), each with an SSH NetworkService and a raw-TCP
    NetworkSerialPort. No speed field: QEMU serial has no baud."""
    owrt_place, client_place = spec.places
    return f"""\
## Generated by lib/labgrid_vlab.py — lane {spec.lane!r}. One virtual lab,
## two places. Edit scripts/virtual-lab.py labgrid-export instead.
## (## not #: exporter configs are Jinja templates, and a single # line is
## a Jinja line statement there, not a comment.)
{owrt_place}:
  NetworkService:
    address: {spec.owrt_address}
    port: {SSH_PORT}
    username: root
  NetworkSerialPort:
    host: {spec.serial_host}
    port: {spec.serial_port_owrt}
{client_place}:
  NetworkService:
    address: {spec.client_address}
    port: {SSH_PORT}
    username: debian
  NetworkSerialPort:
    host: {spec.serial_host}
    port: {spec.serial_port_client}
"""


def _pid_check(pidfile: str, marker: str) -> str:
    """Kill only if the pidfile's process cmdline contains our marker —
    never kill by pattern or a recycled pid. ``pidfile`` is a shell
    expression evaluated on the VM host."""
    return (
        f'if [ -f {pidfile} ]; then '
        f'pid=$(cat {pidfile}); '
        f'if [ -n "$pid" ] && grep -qa "{marker}" /proc/$pid/cmdline 2>/dev/null; then '
        f'kill "$pid" 2>/dev/null || true; '
        f'fi; rm -f {pidfile}; '
        f'fi'
    )


def export_start_script(spec: VlabExportSpec, workdir: str,
                        owrt_serial_sock: str, client_serial_sock: str) -> str:
    """Shell script run ON the VM host: start socat relays + exporter.

    ``workdir`` may contain ``~`` — it is expanded at runtime with the
    same idiom scripts/virtual-lab.py uses everywhere else. The serial
    socket arguments are shell path expressions relative to nothing
    (pass what the VM host understands, e.g. the ``$(eval printf …)``
    expressions from virtual-lab's path helpers).

    Idempotent: existing pidfiles are validated and reused. Verifies the
    relays actually listen before declaring success.
    """
    _check_lane(spec.lane)
    owrt_place, client_place = spec.places
    exporter_pid = '"$run/labgrid-exporter.pid"'
    marker = spec.lane
    return f"""set -eu
workdir={shlex.quote(workdir)}
workdir=$(eval printf '%s' "$workdir")
run="$workdir/run"
mkdir -p "$run" "$workdir/logs"

ensure_relay() {{
  pidfile=$1; port=$2; sock=$3
  if [ -f "$pidfile" ] && grep -qa "{marker}" /proc/$(cat "$pidfile")/cmdline 2>/dev/null; then
    return 0
  fi
  rm -f "$pidfile"
  nohup socat TCP-LISTEN:$port,bind={spec.serial_host},reuseaddr,fork \
    UNIX-CONNECT:"$sock" >/dev/null 2>&1 &
  echo $! > "$pidfile"
}}

ensure_relay "$run/labgrid-socat-owrt.pid" {spec.serial_port_owrt} {owrt_serial_sock}
ensure_relay "$run/labgrid-socat-client.pid" {spec.serial_port_client} {client_serial_sock}

sleep 0.3
for port in {spec.serial_port_owrt} {spec.serial_port_client}; do
  if ! (exec 3<>/dev/tcp/127.0.0.1/$port) 2>/dev/null; then
    echo "FAIL: serial relay on port $port did not come up" >&2
    exit 1
  fi
done

{_pid_check(exporter_pid, marker)}

cat > "$run/labgrid-exporter.yaml" <<'LGEOF'
{exporter_config_yaml(spec)}LGEOF

nohup labgrid-exporter -c {spec.coordinator} -n vlab-{spec.lane} "$run/labgrid-exporter.yaml" \\
  >>"$workdir/logs/labgrid-exporter.log" 2>&1 &
echo $! > {exporter_pid}
sleep 1
if ! grep -qa "{marker}" /proc/$(cat {exporter_pid})/cmdline 2>/dev/null; then
  echo "FAIL: labgrid-exporter died at startup (see $workdir/logs/labgrid-exporter.log)" >&2
  tail -5 "$workdir/logs/labgrid-exporter.log" >&2 || true
  exit 1
fi

echo "labgrid places exported:"
echo "  {owrt_place}  (serial tcp://{spec.serial_host}:{spec.serial_port_owrt})"
echo "  {client_place}  (serial tcp://{spec.serial_host}:{spec.serial_port_client})"
"""


def export_stop_script(spec: VlabExportSpec, workdir: str) -> str:
    """Shell script run ON the VM host: stop exporter + relays."""
    _check_lane(spec.lane)
    marker = spec.lane
    return f"""set -u
workdir={shlex.quote(workdir)}
workdir=$(eval printf '%s' "$workdir")
run="$workdir/run"
{_pid_check('"$run/labgrid-exporter.pid"', marker)}
{_pid_check('"$run/labgrid-socat-owrt.pid"', marker)}
{_pid_check('"$run/labgrid-socat-client.pid"', marker)}
echo "labgrid export for lane {spec.lane!r} stopped"
"""


# ─── client side (test machines) ──────────────────────────────────────────

import subprocess  # noqa: E402  (client side only; host side is script-gen)

_FIELD_RE = re.compile(r"(\w+)=('[^']*'|[^\s,]+)")


def parse_resources(output: str) -> dict[str, dict[str, str]]:
    """Parse `labgrid-client -p PLACE resources` output into
    ``{ResourceClass: {field: value}}`` for the fields we consume.

    Input shape (one line per resource):
        NetworkSerialPort: host='127.0.0.1', port=46000
        NetworkService: address='10.99.99.1', port=22, username='root'
    """
    resources: dict[str, dict[str, str]] = {}
    for line in output.splitlines():
        if ":" not in line or "=" not in line:
            continue
        cls, _, fields = line.partition(":")
        parsed = {}
        for m in _FIELD_RE.finditer(fields):
            key, val = m.group(1), m.group(2)
            if len(val) >= 2 and val.startswith("'") and val.endswith("'"):
                val = val[1:-1]
            parsed[key] = val
        if cls.strip() and parsed:
            resources[cls.strip()] = parsed
    return resources


def resolve_serial(coordinator: str, place: str,
                   runner=subprocess.run) -> tuple[str, int]:
    """(host, port) of a place's NetworkSerialPort, via labgrid-client."""
    cmd = ["labgrid-client", "-x", coordinator, "-p", place, "resources"]
    proc = runner(cmd, capture_output=True, text=True, timeout=15)
    if proc.returncode != 0:
        raise VlabExportError(
            f"labgrid-client resources on place {place!r} failed "
            f"(rc={proc.returncode}): {(proc.stderr or '').strip()[:200]}"
        )
    res = parse_resources(proc.stdout or "")
    nsp = res.get("NetworkSerialPort")
    if not nsp or "host" not in nsp or "port" not in nsp:
        raise VlabExportError(
            f"place {place!r} exports no NetworkSerialPort (has: {sorted(res)})"
        )
    return nsp["host"], int(nsp["port"])
