#!/usr/bin/env python3
"""Generate docs/user-stories.generated.md from the story/tip marks on tests.

Static scan (no test run needed): walks the test tree, reads
``pytest.mark.story("ID")`` / ``pytest.mark.tip("TIP-XX")`` from module
``pytestmark`` blocks and per-test decorators, joins with
``docs/story-catalog.yml``, and renders:

  * per-persona story tables (story -> proving tests -> status)
  * the TIP conformance matrix (spec item -> proving tests)
  * coverage stats

Marks are the single source of truth; this file is generated — do not edit
by hand. Regenerate:  python3 scripts/story-coverage.py
"""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TEST_ROOTS = ("tests", "conwrt", "installer")
OUT = REPO / "docs" / "user-stories.generated.md"

PERSONA_TITLES = {
    "guest": "Guest — “I just paid, let me online”",
    "owner": "Owner — “My router earns while I sleep”",
    "merchant": "Merchant — “Payouts are correct and provable”",
    "operator": "Operator — “The bench tells me the truth”",
    "maintainer": "Maintainer — “Releases and parity hold”",
}
PERSONA_ORDER = list(PERSONA_TITLES)

STORY_RE = re.compile(r'pytest\.mark\.story\("([A-Z]+\d+)"\)')
TIP_RE = re.compile(r'pytest\.mark\.tip\("(TIP-\d+)"\)')


def load_catalog() -> dict[str, dict[str, str]]:
    catalog: dict[str, dict[str, str]] = {}
    line_re = re.compile(
        r'^\s*([A-Z]+\d+):\s*\{persona:\s*(\w+),\s*title:\s*(.+?)\}\s*$'
    )
    for line in (REPO / "docs" / "story-catalog.yml").read_text().splitlines():
        m = line_re.match(line)
        if m:
            catalog[m.group(1)] = {"persona": m.group(2), "title": m.group(3)}
    return catalog


def scan_tests() -> dict[str, dict[str, list[str]]]:
    """file -> {"stories": [...], "tips": [...]}"""
    found: dict[str, dict[str, list[str]]] = {}
    for root in TEST_ROOTS:
        base = REPO / root
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("test_*.py")):
            rel = path.relative_to(REPO).as_posix()
            text = path.read_text(errors="replace")
            stories = sorted(set(STORY_RE.findall(text)))
            tips = sorted(set(TIP_RE.findall(text)))
            if stories or tips:
                found[rel] = {"stories": stories, "tips": tips}
    return found


def main() -> int:
    catalog = load_catalog()
    marks = scan_tests()

    story_tests: dict[str, list[str]] = defaultdict(list)
    tip_tests: dict[str, list[str]] = defaultdict(list)
    for rel, info in marks.items():
        for story in info["stories"]:
            story_tests[story].append(rel)
        for tip in info["tips"]:
            tip_tests[tip].append(rel)

    unmarked = sorted(
        rel for rel, info in marks.items() if not info["stories"]
    )
    lines: list[str] = [
        "# User stories — generated coverage map",
        "",
        "<!-- GENERATED by scripts/story-coverage.py from pytest.mark.story/tip",
        "     on the tests. Do not edit by hand; regenerate instead.",
        "     Hand-written narrative version: docs/user-stories.md -->",
        "",
        f"- test files carrying marks: **{len(marks)}**",
        f"- stories with at least one proving test: **{sum(1 for s in catalog if story_tests.get(s))}/{len(catalog)}**",
        f"- TIPs exercised: **{len(tip_tests)}** ({', '.join(sorted(tip_tests)) or 'none yet'})",
        "",
        "Selection: `pytest --story G2` · `pytest --tip TIP-01` · both combine (AND)",
        "",
    ]

    for persona in PERSONA_ORDER:
        stories = [s for s, c in catalog.items() if c["persona"] == persona]
        if not stories:
            continue
        lines += [f"## {PERSONA_TITLES[persona]}", "", "| ID | Story | Proving tests | Status |", "|----|-------|---------------|--------|"]
        for story in stories:
            tests = story_tests.get(story, [])
            status = "Covered" if tests else "Gap"
            test_cell = "<br>".join(f"`{t}`" for t in tests) if tests else "—"
            lines.append(f"| {story} | {catalog[story]['title']} | {test_cell} | {status} |")
        lines.append("")

    if tip_tests:
        lines += ["## TIP conformance matrix", "", "| TIP | Proving tests |", "|-----|---------------|"]
        for tip in sorted(tip_tests):
            lines.append(f"| {tip} | {'<br>'.join(f'`{t}`' for t in tip_tests[tip])} |")
        lines.append("")

    if unmarked:
        lines += [
            "## Tip-marked files with no story",
            "",
            "Spec coverage without a user story — assign one or accept as pure conformance:",
            "",
        ]
        lines += [f"- `{rel}`" for rel in unmarked]
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO)} ({len(marks)} marked files, {len(tip_tests)} TIPs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
